#!/bin/csh

set semester=18fall
set course=401_601
set assignment=nfa-e

#
# THE REST OF THE FILE SHOULD REMAIN UNCHANGED
#

/home/turing/karonis/Classes/ForStudents/submit $semester $user $assignment $1 $course
